# Generated by Django 5.1.6 on 2025-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_book_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=500),
        ),
    ]
