# Generated by Django 5.1.6 on 2025-04-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_author_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="new_author",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.author"
            ),
        ),
    ]
