# Generated by Django 5.1.6 on 2025-05-02 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_book_new_author_alter_book_author"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="BooksAuthor",
        ),
    ]
